// Lightweight PDF generation using jsPDF
// Generates a simple summary PDF for a career application
import jsPDF from "jspdf";

export function generateApplicationPDF(app) {
  const doc = new jsPDF();
  const marginLeft = 15;
  let cursorY = 20;

  const addLine = (label, value) => {
    doc.setFontSize(12);
    doc.text(`${label}:`, marginLeft, cursorY);
    doc.text(String(value || "-"), marginLeft + 45, cursorY);
    cursorY += 10;
  };

  // Header with styling
  doc.setFillColor(79, 70, 229); // indigo-600
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text("NDH Tech", marginLeft, 18);
  doc.setFontSize(14);
  doc.text("Career Application", marginLeft, 28);
  
  cursorY = 55;
  doc.setTextColor(30, 41, 59); // slate-800

  // Submission date
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text(`Submitted: ${new Date(app.id).toLocaleString()}`, marginLeft, cursorY);
  cursorY += 15;

  // Applicant details section
  doc.setFontSize(14);
  doc.setTextColor(79, 70, 229);
  doc.text("Applicant Details", marginLeft, cursorY);
  cursorY += 10;
  
  doc.setDrawColor(226, 232, 240);
  doc.line(marginLeft, cursorY, 195, cursorY);
  cursorY += 10;

  doc.setTextColor(30, 41, 59);
  addLine("Full Name", app.name);
  addLine("Email", app.email);
  addLine("Phone", app.phone || "-");
  addLine("Position", app.position);
  addLine("Resume File", app.resumeName);

  cursorY += 5;

  // Message section (if present)
  if (app.message) {
    doc.setFontSize(14);
    doc.setTextColor(79, 70, 229);
    doc.text("Cover Message", marginLeft, cursorY);
    cursorY += 10;
    
    doc.setDrawColor(226, 232, 240);
    doc.line(marginLeft, cursorY, 195, cursorY);
    cursorY += 8;

    doc.setFontSize(11);
    doc.setTextColor(51, 65, 85);
    const wrapped = doc.splitTextToSize(String(app.message), 175);
    doc.text(wrapped, marginLeft, cursorY);
  }

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text("This document was auto-generated by NDH Tech Career Portal", marginLeft, 285);

  // Save
  const safeName = (app.name || "applicant").replace(/[^a-z0-9-_]+/gi, "_");
  const safePos = (app.position || "position").replace(/[^a-z0-9-_]+/gi, "_");
  doc.save(`NDH_Application_${safePos}_${safeName}.pdf`);
}
